import type { Metadata } from "next";
import {
  StaticStyles,
  // HydrateStyles,
} from '@cssfn/cssfn-react/server'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <StaticStyles />
        {/* <HydrateStyles /> */}
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
